trigger:
- main

pool: 'MyLocalPool'

variables:
- group: github-att

stages:
- stage: Build
  displayName: 'Build and Push'
  jobs:
  - job: Build
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'acr-service-connection'
        repository: 'ranacse/sales-dashboard-v1'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
          $(Build.BuildId)

- stage: Deploy
  displayName: 'Deploy to AKS'
  dependsOn: Build
  jobs:
  - job: DeployJob
    steps:
    - powershell: |
        git config --global user.email "saif99cse@gmail.com"
        git config --global user.name "saif99cse"
        git clone https://$(token)@github.com/ranacse/html-manifest-repo.git
        cd html-manifest-repo
        (Get-Content deployment.yaml) -replace 'ranacse/sales-dashboard-v1:.*', "ranacse/sales-dashboard-v1:$(Build.BuildId)" | Set-Content deployment.yaml
        git add deployment.yaml
        git commit -m "Update tag $(Build.BuildId)"
        git push origin main
      displayName: 'Update Git Manifest'

    - powershell: |
        kubectl set image deployment/myapp-deployment myapp-container=ranacse/sales-dashboard-v1:$(Build.BuildId)
      displayName: 'Force Update AKS Cluster'