name: Build and Deploy to AKS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Build Docker image with unique tag
      run: |
        docker build -t ranaacrregistry.azurecr.io/myapp:${{ github.sha }} .
        docker build -t ranaacrregistry.azurecr.io/myapp:latest .
    
    - name: Push to Azure Container Registry
      run: |
        echo "${{ secrets.AZURE_REGISTRY_PASSWORD }}" | docker login -u ranaacrregistry --password-stdin ranaacrregistry.azurecr.io
        docker push ranaacrregistry.azurecr.io/myapp:${{ github.sha }}
        docker push ranaacrregistry.azurecr.io/myapp:latest
